import { DripRecipe } from './types';

export const MOCK_RECIPES: DripRecipe[] = [
    // BYSN Standard Drip (細く中心に注ぐスタイル)
    {
        id: 'recipe-001',
        name: 'BYSN Standard Drip',
        beanName: 'G2B8',
        beanAmountGram: 20,
        totalWaterGram: 320,
        totalDurationSec: 180,
        purpose: '試飲会用スタンダード',
        description: 'できるだけお湯を細く、中心に１円玉くらいの円を描きながら注ぐ淹れ方。丁寧な抽出で酸味と甘みのバランスを引き出します。',
        createdAt: '2023-10-27T10:00:00Z',
        updatedAt: '2023-10-27T10:00:00Z',
        isDefault: true,
        steps: [
            {
                id: 'step-1',
                startTimeSec: 0,
                title: '蒸らし',
                description: '中心に細くお湯を注ぎ、１円玉くらいの円を描きながら全体を湿らせます。20秒蒸らします。',
                targetTotalWater: 20,
                note: '粉全体が均一に膨らむのを確認',
            },
            {
                id: 'step-2',
                startTimeSec: 20,
                title: '1投目',
                description: 'できるだけ細く、中心に１円玉くらいの円を描きながらゆっくり注ぎます。',
                targetTotalWater: 200,
                note: '注湯スピードは一定に保つ',
            },
            {
                id: 'step-3',
                startTimeSec: 85,
                title: '2投目',
                description: '同様に細く、中心に１円玉くらいの円を描きながら注ぎ足します。',
                targetTotalWater: 280,
                note: '水位が下がりすぎないタイミングで',
            },
            {
                id: 'step-4',
                startTimeSec: 115,
                title: '3投目',
                description: '最後まで細く丁寧に、中心に１円玉くらいの円を描きながら注ぎきります。',
                targetTotalWater: 320,
                note: '最後まで一定のスピードで',
            },
            {
                id: 'step-5',
                startTimeSec: 130,
                title: '落ち切り待ち',
                description: 'ドリッパーからお湯が完全に落ち切るのを待ちます。',
                note: '目標抽出時間: 3分30秒前後',
            },
        ],
    },

    // 井崎流ハンドドリップ術 (new)
    {
        id: 'recipe-003',
        name: '井崎流ハンドドリップ術',
        beanName: 'G2B8',
        beanAmountGram: 20,
        totalWaterGram: 300,
        totalDurationSec: 180,
        purpose: 'アジア人初の世界チャンピオンの淹れ方',
        description: '井崎流のハンドドリップレシピ。4回注ぎで合計300gの抽出。',
        createdAt: '2023-11-01T10:00:00Z',
        updatedAt: '2023-11-01T10:00:00Z',
        isDefault: true,
        steps: [
            {
                id: 'step-1',
                startTimeSec: 0,
                title: '蒸らし（1投目）',
                description: '細く注いで60g、その後撹拌',
                targetTotalWater: 60,
                note: '撹拌（ドリッパーを軽く回す）',
            },
            {
                id: 'step-2',
                startTimeSec: 60,
                title: '2投目',
                description: '太めの注湯で60g',
                targetTotalWater: 120,
            },
            {
                id: 'step-3',
                startTimeSec: 90,
                title: '3投目',
                description: '同様に60g',
                targetTotalWater: 180,
            },
            {
                id: 'step-4',
                startTimeSec: 120,
                title: '4投目／仕上げ',
                description: '残り120g注ぐ、その後撹拌 → 落ちきり',
                targetTotalWater: 300,
                note: '撹拌（ドリッパーを軽く回す）',
            },
        ],
    },
];
