import { DripRecipe } from './types';

export const MOCK_RECIPES: DripRecipe[] = [
    // BYSN Standard Drip (細く中心に注ぐスタイル) - 1人前基準
    {
        id: 'recipe-001',
        name: 'BYSN Standard Drip',
        beanName: 'BYSNドリップパック',
        beanAmountGram: 10,
        totalWaterGram: 160,
        totalDurationSec: 180,
        purpose: '試飲会用スタンダード',
        description: 'できるだけお湯を細く、中心に１円玉くらいの円を描きながら注ぐ淹れ方。丁寧な抽出で酸味と甘みのバランスを引き出します。',
        createdAt: '2023-10-27T10:00:00Z',
        updatedAt: '2023-10-27T10:00:00Z',
        isDefault: true,
        steps: [
            {
                id: 'step-1',
                startTimeSec: 0,
                title: '蒸らし',
                description: '粉全体にまんべんなくお湯を注いで均一に湿らせます。20秒蒸らします。',
                targetTotalWater: 20,
                note: '粉全体が均一に膨らむのを確認',
            },
            {
                id: 'step-2',
                startTimeSec: 20,
                title: '1投目',
                description: 'できるだけ細く、中心に１円玉くらいの円を描きながらゆっくり注ぎます。',
                targetTotalWater: 100,
                note: '注湯スピードは一定に保つ',
            },
            {
                id: 'step-3',
                startTimeSec: 85,
                title: '2投目',
                description: '同様に細く、中心に１円玉くらいの円を描きながら注ぎ足します。',
                targetTotalWater: 140,
                note: '水位が下がりすぎないタイミングで',
            },
            {
                id: 'step-4',
                startTimeSec: 110,
                title: '3投目',
                description: '最後まで細く丁寧に、中心に１円玉くらいの円を描きながら注ぎきります。',
                targetTotalWater: 160,
                note: '最後まで一定のスピードで',
            },
            {
                id: 'step-5',
                startTimeSec: 130,
                title: '落ち切り待ち',
                description: 'ドリッパーからお湯が完全に落ち切るのを待ちます。',
                note: '目標抽出時間: 3分秒前後',
            },
        ],
    },

    // 井崎流ハンドドリップ術 - 1人前基準
    {
        id: 'recipe-003',
        name: '井崎流ハンドドリップ術',
        beanName: 'お好みの豆',
        beanAmountGram: 10,
        totalWaterGram: 150,
        totalDurationSec: 180,
        purpose: 'アジア人初の世界チャンピオンの淹れ方',
        description: '井崎流のハンドドリップレシピ。4回注ぎで抽出します。',
        createdAt: '2023-11-01T10:00:00Z',
        updatedAt: '2023-11-01T10:00:00Z',
        isDefault: true,
        steps: [
            {
                id: 'step-1',
                startTimeSec: 0,
                title: '蒸らし（1投目）',
                description: '細く注いで、その後撹拌',
                targetTotalWater: 30,
                note: '撹拌（ドリッパーを軽く回す）',
            },
            {
                id: 'step-2',
                startTimeSec: 60,
                title: '2投目',
                description: '太めの注湯で注ぐ',
                targetTotalWater: 60,
            },
            {
                id: 'step-3',
                startTimeSec: 90,
                title: '3投目',
                description: '同様に注ぐ',
                targetTotalWater: 90,
            },
            {
                id: 'step-4',
                startTimeSec: 120,
                title: '4投目／仕上げ',
                description: '残りを注ぐ、その後撹拌 → 落ちきり',
                targetTotalWater: 150,
                note: '撹拌（ドリッパーを軽く回す）',
            },
        ],
    },
];
